annotate_document/urls.py
from django.urls import path

from . import views

app_name = 'annotate_document'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:document_id>', views.document, name='document'),
    path('view/<int:profile_id>/<int:document_id>', views.view_page, name='view_page'),
    path('search', views.search_entities, name='search'),
    path('link', views.link, name='link'),
    path('list', views.DocumentListView.as_view(), name='document-list'),
    path('info', views.information, name='info'),
    path('review', views.review, name='review'),
    path('complete', views.complete, name='complete'),
    path('signup', views.signup, name='signup'),
    path('update_res', views.update_receive_res, name='updateReceiveRes'),
    path('export/<int:document_id>', views.export, name="export"),
    path('export/', views.export_all, name="export"),
    path('update_annotated', views.update_annotated, name="updateAnnotated"),
    path('tutorial', views.tutorial, name="tutorial"),
    path('help', views.help, name="help"),
    path('instructions', views.instructions, name="instructions"),
    path('delete_link', views.delete_link, name="deleteLink"),
    path('add_doc', views.add_document, name="addDocument"),
    path('update_tut', views.update_tutorial, name="updateTutorial"),
    path('update_instr', views.update_instructions, name="updateInstructions"),
    path('payments', views.get_payments, name="payments"),
    path('user_page', views.user_page, name="userPage"),
    path('video', views.show_video, name="video"),
    path('invitation', views.invitation, name="invitation"),
    path('send-completion', views.send_completion_email, name="sendCompletion"),
    path('opt-out', views.optout, name="opt-out"),
    path('empty', views.no_docs, name="no-docs")
]

annotator/urls.py
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('annotate_document.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path(
        "favicon.ico",
        RedirectView.as_view(url=staticfiles_storage.url("favicon.ico")),
    ),
]

annotate_document/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class SignUpForm(UserCreationForm):
    phone_error = 'Phone number should have the following format: +27121231234.' \

    phone_help = 'Include international dialing codes e.g the South African number ' \
                 '(dialing code +27) 012 123 1234 becomes +27121231234'

    # Phone number validator
    phone_regex = RegexValidator(regex=r'^\+\d{11}$', message=phone_error)

    phone_number = forms.CharField(required=True, max_length=20, validators=[phone_regex], help_text=phone_help,
                                   widget=forms.TextInput(attrs={'type': 'tel',
                                                                 'class': 'form-control',
                                                                 'placeholder': '+27121231234',
                                                                 }))

    consent = forms.BooleanField(required=True, initial=False)
    consentTerms = forms.BooleanField(required=True, initial=False, label="Terms and Privacy")

    def clean_consent(self):
        data = self.cleaned_data['consent']
        if not data:
            raise ValidationError("You must give consent for your participation in the survey")

    class Meta:
        model = User
        fields = ('username', 'phone_number', 'password1', 'password2', 'consent')
        widgets = {
            'username': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'password': forms.PasswordInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'password2': forms.PasswordInput(
                attrs={
                    'class': 'form-control'
                }
            )
        }

annotate_document/views.py
import json
from itertools import chain
from random import sample, randint
from re import sub, match
import logging

from django.db.models import IntegerField, Sum, Case, Count, When, F, Q
from django.conf import settings
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.http import JsonResponse, HttpResponseForbidden
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404, Http404
from django.utils.decorators import method_decorator
from django.utils.timezone import now
from django.views.generic.list import ListView

from .decorators import admin_approval_required
from .models import DocumentSegment, Mention, Entity, Profile, Link, DocumentAnnotation, OptOut, SuggestedEdit, \
    VerifyLanguage
from .forms import SignUpForm

logger = logging.getLogger(__name__)


def find_html(text, term, offset=0):
    if len(term) < 1:
        return 0, 0
    start_pos = text.find(term[0], offset)
    while start_pos != -1:
        cursor = 1
        term_match = text[start_pos]
        html_offset = 0
        while cursor < len(term) and start_pos + cursor + html_offset < len(text) and \
                text[start_pos + cursor + html_offset] == term[cursor]:
            term_match += text[start_pos + cursor + html_offset]
            cursor += 1

            if start_pos + cursor + html_offset < len(text) and text[start_pos + html_offset + cursor] == "<":
                html_match = match(r'(</?.*?>)+', text[start_pos + html_offset + cursor:])
                if html_match:
                    html_offset += len(html_match.group(0))
        if term_match == term:
            return start_pos, start_pos + html_offset + cursor
        else:
            start_pos = text.find(term[0], start_pos + cursor + html_offset)
    return -1, -1


def highlight_mention_occurrence(request, mention, mention_id, text):
    name = mention.get('mention__text')
    occurrence = mention.get('mention__occurrence')
    start_html = f'<mark id="prev-{mention_id}" class="green">'
    end_html = '</mark>'
    offset = 0
    count = 0
    start_pos = 0
    while count < occurrence and start_pos != -1:
        start_pos, end_pos = find_html(text, name, offset)
        if start_pos != -1:
            count += 1
        else:
            logger.error(f"Failed to highlight: {name} in {text}")
            if request:
                messages.error(request,
                               f"Oops, Something has gone wrong and we failed to highlight <b>{name}</b>. But  "
                               f"don't worry <em>it has still been saved so you can carry on annotating</em>.",
                               extra_tags='safe')
            return text
        offset = end_pos

    return text[:start_pos] + start_html + text[start_pos:end_pos] + end_html + text[end_pos:]


def highlight_mention(mention, mention_id, text_list):
    pos = mention["mention__start_position"]
    cursor = 0
    index = 0
    start_html = f'<mark id="prev-{mention_id}" class="green">'
    end_html = '</mark>'
    line_offset = len(text_list[index]) - text_list[index].count("&gt") - 2 * text_list[index].count("&lt")
    while pos > cursor + line_offset and index < len(text_list) - 1:
        index += 1
        cursor += len(text_list[index - 1]) - text_list[index].count("&gt") - text_list[index].count("&lt")
        line_offset = len(text_list[index]) - text_list[index].count("&gt") - text_list[index].count("&lt")

    # Calculate start offset in segment
    new_pos, new_end_pos = find_html(text_list[index], mention['mention__text'].split(' ')[0],
                                     max(0, pos - cursor - len(mention['mention__text'])))
    start_index = index
    end_pos = cursor + new_pos + len(mention['mention__text'])
    end_counter = len(text_list[index]) - new_pos
    line_offset = len(text_list[index]) - 2 * text_list[index].count("&gt") - 2 * text_list[index].count("&lt")
    while end_pos > cursor + line_offset and index < len(text_list) - 1:
        cursor += line_offset
        end_counter += len(text_list[index])
        index += 1
    # Update end_pos
    end_term = mention['mention__text'].split(' ')[-1]
    _, no_html_end = find_html(text_list[index], end_term)
    end_local = max(end_pos - cursor, no_html_end)

    end_index = index
    # Add end html
    text_list[end_index] = text_list[end_index][:end_local] + end_html + text_list[end_index][end_local:]
    # Add start html
    text_list[start_index] = text_list[start_index][:new_pos] + start_html + text_list[start_index][new_pos:]
    return text_list


def split_document(size, full_document, request=None, mentions=[], annotated_lines='', use_occurrences=True):
    num_line = 0
    end_html = '<br>'
    new_text = ''
    cursor = 0
    full_document = full_document.replace('\n', '')

    # Split Text into lines
    split_text = []
    while cursor + size < len(full_document):
        break_point = full_document.rfind(' ', cursor, min(cursor + size, len(full_document)))
        if break_point == -1:
            break_point = len(full_document)
        split_text.append(full_document[cursor: break_point])
        cursor = break_point
        num_line += 1
    split_text.append(full_document[cursor: len(full_document)])
    num_line += 1

    # Add highlights
    if not use_occurrences:
        for i in range(len(mentions)):
            split_text = highlight_mention(mentions[i], i, split_text)

    # Add checkboxes
    new_text = ''
    num_line = 0
    for line in split_text:
        new_text += line + \
                    f"<input type='checkbox' class='annotate_checkbox float-right mr-2' id='line-{num_line}' value=1 onclick='app.check_annotated()'" \
                    f"{'checked' if annotated_lines and num_line < len(annotated_lines) and annotated_lines[num_line] == '1' else ''}>" \
                    + end_html
        num_line += 1
    # Add highlights
    if use_occurrences:
        for i in range(len(mentions)):
            new_text = highlight_mention_occurrence(request, mentions[i], i, new_text)
    return new_text, num_line


@login_required
@admin_approval_required
def index(request):
    documents = DocumentAnnotation.objects.filter(profile=request.user.profile).order_by('seq')
    # if no documents assigned
    if not documents.first() or request.user.profile.refresh:
        assign_all_documents(request)
        documents = DocumentAnnotation.objects.filter(profile=request.user.profile).order_by('seq')
    doc = documents.first()
    if not doc:
        return redirect("annotate_document:no-docs")
    return document(request, doc.document.id)


@login_required
@admin_approval_required
def document(request, document_id):
    if not DocumentAnnotation.objects.all().filter(profile=request.user.profile,
                                                   document__id=document_id).exists():
        raise Http404

    document = get_object_or_404(DocumentSegment, pk=document_id)
    ann_documents = DocumentAnnotation.objects.all().filter(profile=request.user.profile).order_by('seq',
                                                                                                   'document__id')
    ann_document = ann_documents.get(document__id=document_id)
    mentions = Link.objects.all().filter(created_by=request.user.profile, mention__document=document)
    mention_list = list(
        mentions.values('mention__text', 'entity__name', 'mention__start_position', 'mention__occurrence'))
    mention_list.sort(key=lambda x: x["mention__start_position"], reverse=True)
    doc_index = [d.get('document__id') for d in ann_documents.values('document__id')].index(document_id) + 1
    document_lines, num_lines = split_document(settings.MAX_LINE_LEN, document.body, request=request,
                                               mentions=mention_list,
                                               annotated_lines=ann_document.annotated_lines)
    if ann_document.annotated_lines == '' or len(ann_document.annotated_lines) < num_lines:
        ann_document.annotated_lines = '0' * num_lines
        ann_document.save()
    id_list = [d.document.id for d in ann_documents]
    current = id_list.index(document_id)
    prev_doc = id_list[current - 1] if current > 0 else None
    next_doc = id_list[current + 1] if current < (len(id_list) - 1) else None

    annotated = 'true' if ann_document.annotated_lines.count('0') == 0 else 'false'
    context = {'document': document, "prev_mentions": mentions,
               "json_mentions": json.dumps(mention_list),
               "prev_doc": prev_doc, "next_doc": next_doc, 'document_lines': document_lines,
               'num_lines': num_lines, "annotated": annotated, "doc_index": doc_index,
               "num_docs": ann_documents.count()}
    return render(request, 'annotate_document/index.html', context)


@login_required
@staff_member_required
def view_page(request, profile_id, document_id):
    if not DocumentAnnotation.objects.all().filter(profile__id=profile_id,
                                                   document__id=document_id).exists():
        raise Http404
    user_profile = Profile.objects.get(pk=profile_id)
    document = get_object_or_404(DocumentSegment, pk=document_id)
    ann_documents = DocumentAnnotation.objects.all().filter(profile=user_profile).order_by('seq', 'document__id')
    ann_document = ann_documents.get(document__id=document_id)
    mentions = Link.objects.all().filter(created_by=user_profile, mention__document=document)
    mention_list = list(
        mentions.values('mention__text', 'entity__name', 'mention__start_position', 'mention__occurrence'))
    mention_list.sort(key=lambda x: x["mention__start_position"], reverse=True)

templates/annotate_document/documentannotation_list.html
{% extends 'annotate_document/base.html' %}
{% load annotate_extras %}

{% block header %}
		<h1>Document List</h1>
{% endblock %}

{% block content %}
<table class="table table-borderless">
    <thead class="thead-light">
        <tr>
            <th scope="col">Document</th>
            <th scope="col">Complete</th>
            <th scope="col">Unannotated Lines</th>
        </tr>
    </thead>
{% for document in object_list %}
        <tr>
            <td><a href="{%url 'annotate_document:document' document.document.id %}">{{ document.document.title }}</a></td>
            <td>{% if '0' in document.annotated_lines %} NO {% else %} YES {% endif %}</td>
            <td>{% if '0' in document.annotated_lines %}{{document.annotated_lines|count:"0"}}{% endif %}</td>
        </tr>
{% empty %}
    <li>No documents yet.</li>
{% endfor %}
</table>
<div class="row">
    <div class="col">
        {% if complete and not annotation_complete%}
        To annotate another document click here: <a href="{% url 'annotate_document:addDocument' %}">Annotate New Document</a><br>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/annotate_document/help.html
{% extends 'annotate_document/help_base.html' %}

{% block header %}
<h1>Help</h1>
{% endblock %}

{% block page_nav %}
<div class="row">
    <div class="col-12">
        <button class="btn btn-primary mb-2" onClick="javascript:history.go(-1);">Back</button>
    </div>
</div>
{% endblock %}

templates/annotate_document/help_base.html
{% extends 'annotate_document/base.html' %}
{% load static %}
{% load annotate_extras %}


{% block content %}
<div class="row">
    <div class="col-md-6">
        <h2>Annotating Documents</h2>
    </div>
    <div class="col-md-6">
        <a  id="prev_btn" class="btn btn-primary mb-2 mt-2 float-right" href="{%url 'annotate_document:video' %}" target="_blank">
            Tutorial Video
        </a>
    </div>
</div>

<h3>1. Overview</h3>
<p>
    For each task we want to find all the names which refer to the same person. To do this we need to find occurrences of
    names (or nicknames/aliases) and link them to the person to whom they refer.<br>
    In the document the following terms are used:
    <ul>
        <li><b>mention</b>: A particular occurrence of a name within the text (<em>Shaka Zulu</em> or
            <em>Sigidi kaSenzangakhona</em>).
        </li>
    <li><b>entity</b>: A person (<em>Shaka kaSenzangakhona</em>).</li>
    </ul>
    The image below shows the basic structure of each document to be annotated.
</p>
<img src="{% static 'annotate_document/images/annotator1.jpg' %}" alt="Overview Image" class="mb-3">

<h3> 2. Select a name(mention)</h3>
<p>
    To link a name(mention) to an entity. Start by selecting the name from the textbox.<br>
    Please make sure you highlight the whole name and try not to include any spaces before/after.<br>
    Please include any titles that appear as part of the name for example <em>chief Senzangakhona</em> rather than just
    <em>Senzangakhona</em>.
</p>
<img src="{% static 'annotate_document/images/annotator-2.jpg' %}" alt="Select name Image" class="mb-3">

<h3> 3. Highlight the name</h3>
<p>
    Clicking <b>Highlight</b> will highlight the name.<br>
    The name now shows up as a selected mention along with its position in the document.<br>
    You can close the pop-up and repeat this process to highlight all the names that refer to the same person(entity).
</p>
<img src="{% static 'annotate_document/images/annotator-3.jpg' %}" alt="Select name Image" class="mb-3"><br>

<h3>4. Ignoring a selected name</h3>
<p>
If you accidentally highlight a mention and don't want to link it then you can uncheck the checkbox next to the
    mention in the selected mentions section.<br>
If you want to clear all the selected mentions you close the select person pop-up and click the <b>clear</b> button.
</p>
<img src="{% static 'annotate_document/images/annotator-5.jpg' %}" alt="Select name Image" class="mb-3"><br>

<h3>5. Select a person</h3>
<p>
    Use the search bar to search for the person who being referred to by the selected name(s).<br>
    When searching it is best to try searching for the simplest form of the person's name. If that doesn't give the
    correct result try searching for just the first few letters of their name.
    A list of the people who possibly match your search will be shown as well as an option to create a new entity if
    there are no matches.<br>
    For each of the entities you can click on <b>Description</b> or <b>Alias</b> to display/hide more infromation about the
    entity or the previous name that have been associated with the entity.
</p>
<img src="{% static 'annotate_document/images/annotator-6.jpg' %}" alt="Select an entity"><br>
<h3>5.1. Edit Candidate Entity</h3>
<p>
    If you are using an existing entity but you think there is a mistake in either the entity name or description
    you can suggest changes. By clicking the <b>Suggest Edit</b> button. This opens up an <b>Edit Entity</b> form.<br>
    To edit the name or description check the relevant box and edit the text box.
</p>
<img src="{% static 'annotate_document/images/annotator-6-1.jpg' %}" alt="Select an entity" class="mb-3"><br>

<h3>6. Create a new entity</h3>
<p>
    If the names selected match none of the entities please try searching for other possible names. If a match is still
    not found then you may need to create a new entity.<br>
    Selecting the <b>Create New</b> option will open a form for creating a new entity.<br>
    The name field is automatically filled in. However, you can edit if it isn't suitable.<br>
    If you edit the name please use the most complete name for the entity e.g "Shaka kaSenzangakhona" instead of "Shaka Zulu".<br>
    The date of birth and date of death fields are optional.<br>
    The description field is automatically filled in although you can edit it if you can provide a better description.
</p>
<img class="mb-3" src="{% static 'annotate_document/images/annotator-6.jpg' %}" alt="Select an entity" class="mb-3"><br>

<h3>7. Link the mention(s) with the entity</h3>
<p>
    Once you have selected an entity or filled in the form for a new entity you can click <b>Link</b> to link them.
</p>
<img src="{% static 'annotate_document/images/annotator-7.jpg' %}" alt="Select an entity" class="mb-3"><br>

<h3>8. Complete line</h3>
<p>
    Once you have annotated all, if any, of the names in a row please check the checkbox at the end of the row.
</p>
<img src="{% static 'annotate_document/images/annotator-8.jpg' %}" alt="Select an entity" class="mb-3"><br>

<h3>9. Delete/View Link</h3>
<p>
    To check if a name is correctly linked click on the highlighted text to view the name of the person it has been
    linked to.<br>
    If the name is linked to the wrong person you can delete the link by pressing delete then recreate the link.
</p>
<img src="{% static 'annotate_document/images/annotator1-del.jpg' %}" alt="Select an entity" class="mb-3"><br>

<h3>10. Completing the annotation of the document</h3>
<p>
    Repeat the above steps to link all the names in the document.<br>
    Once all the lines are checked you can move on to the next document.
</p>
<img src="{% static 'annotate_document/images/annotator-9.jpg' %}" alt="Select an entity" class="mb-3"><br>

<h3> Contact </h3>
<p>If you have any further questions please send an email to: <a href="mailto:{% settings_value 'EMAIL_ADMIN' %}">{% settings_value "EMAIL_ADMIN" %}</a></p>

{% block page_nav %}{% endblock %}
{% endblock %}

templates/annotate_document/information.html
{% extends 'annotate_document/base.html' %}

{% block header %}
		<h1>Project Overview</h1>
{% endblock %}

{% block content %}
<h2>Project Description</h2>
<p>
    It is not always clear which person a name is referring to. This could be because many people share the same name or
    because one person has multiple names. Working out who us being referred to within historical documents can be a
    major issue especially when there are thousands of documents where this occurs. One way to try and solve this problem
    is to train computer programs to automatically detect names and determine to whom they refer. However, programs like
    this require large amounts of data.
</p>

<h2> How does this survey fit in?</h2>
<p>
    In order to learn to detect names and associate them with a person the program requires many examples of people's
    names and to whom they refer. In this survey you will be required to identify people names from within some text and
    "<b>link</b>" them to the people to whom they refer. For example the names Shaka Zulu and King Shaka refer to the same
    person.
</p>

<h2>Document Text</h2>
<p>The texts used are collected by using Optical Character Recognition (OCR) to extract the text from scanned PDFs of
    the historical documents. Unfortunately, the OCR process tends to introduce a number of errors in the text and it is
    infeasible to manually remove all errors. Please try and ignore the OCR errors as far as possible</p>

<h2>Payment</h2>
<p>
    You will be paid based on the number of links you create at a rate of <b>R 0.60 per link</b>. Since different documents contain different amounts of
    names they will be randomly assigned to participants. Every document will be given to at least three users.
    A link will only be created when all three users create the same link between a name and a person. Thus,
    you wil only be paid for links you create that are in agreement with links created by other users. Once all the
    documents have been annotated you will receive an SMS with a code which can be used to receive your payment.
</p>

<div class="row">
    <div class="col-12">
        <a  class="btn btn-primary float-right mb-2" href="{%url 'annotate_document:instructions' %}">Continue</a>
    </div>
</div>
{% endblock %}

templates/annotate_document/instructions.html
{% extends 'annotate_document/video_base.html' %}

{% block instructions %}
<div class="row">
    <div class="col-12">
        <p>
            Please watch the short video to see how to use the system to link names to the people to whom they refer.<br>
            Once you have watch the video you will be able to move on to the tutorial.
        </p>
    </div>
</div>
{% endblock %}

{% block navigation %}
<div class="row">
    <div class="col-6">
        <a  id="prev_btn" class="btn btn-secondary mb-2 mt-2 float-left" href="{%url 'annotate_document:info' %}">Back</a>
    </div>
    <div class="col-6 float-right">
        <a  id="next_btn" class="btn btn-primary mb-2 mt-2 float-right {% if not user.profile.tutorial_video %}hide{% endif %}" href="{%url 'annotate_document:updateInstructions' %}">Start Tutorial</a>
    </div>
</div>
{% endblock %}

templates/annotate_document/nopages.html
{% extends 'annotate_document/base.html' %}

{% block header %}
<h1>No Documents</h1>
{% endblock %}
{% block navList %}
<li></li>
<li><a class="float-right" href="{% url 'annotate_document:document-list' %}">Document List</a></li>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-12">
        <h4>Thanks for coming but all the available documents have been processed.</h4>
    </div>
</div>
{% endblock %}

templates/annotate_document/review.html
{% extends 'annotate_document/base.html' %}
{% load annotate_extras %}

{% block header %}
		<h1>Review</h1>
{% endblock %}

{% block content %}
<p>
    {% if incomplete_documents%}
        <h3>Please finish annotating the following documents</h3><br>
        <table class="table table-borderless">
            <thead class="thead-light">
            <tr>
                <th scope="col">Document</th>
                <th scope="col">Complete</th>
                <th scope="col">Unannotated Lines</th>
            </tr>
            </thead>
            {% for document in incomplete_documents %}
            <tr>
                <td><a href="{%url 'annotate_document:document' document.document.id %}">{{ document.document.title }}</a></td>
                <td>{% if '0' in document.annotated_lines %} NO {% else %} YES {% endif %}</td>
                <td>{% if '0' in document.annotated_lines %}{{document.annotated_lines|count:"0"}}{% endif %}</td>
            </tr>
            {% empty %}
            <li>No documents yet.</li>
            {% endfor %}
        </table>
    {% else %}
        <h3>Thank You, you have annotated all the documents allocated to you!</h3><br>
        <div class="row">
            <div class="col-md-9">
                <form id=”resultsForm” method="post" class="form pb-2 ml-2">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-10">
                            <label for="receiveRes">
                                Would you like to receive information about the results of this project?
                            </label>
                        </div>
                        <div class="col-md-2 float-left">
                            <select name="receiveResults" class="form-control ml-2 mr-2 float-left" id="receiveRes">
                                <option value="Yes" {% if receive_res %}selected{% endif %}>Yes</option>
                                <option value="No" {% if not receive_res %}selected{% endif %}>No</option>
                            </select>
                        </div>
                    </div>
                    <div id="email_form" style="display:none">
                        <div class="row mt-2">
                            <div class="col-md-1">
                                <lable for="emailRes">Email</lable>
                            </div>
                            <div class="col-md-11">
                                <input id="emailRes" type="email" class="form-control ml-2 mr-2">
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <button id="email_btn" type="button" class="btn btn-primary mt-2">Submit</button>
                            </div>
                        </div>
                    </div>
                    <div id="receiveResponse"></div>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col">
                To go back to a continue annotating a document please click here: <a href="{% url 'annotate_document:document-list' %}">Document List</a><br>
                {% if not annotation_complete %}
                    To annotate another document click here: <a href="{% url 'annotate_document:addDocument' %}">Annotate New Document</a><br>
                {% endif %}
                Otherwise please click here to finish: <a href="{% url 'annotate_document:complete' %}">Finish</a>
            </div>
        </div>
    {% endif %}
</p>

<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
<script>
    $("#email_btn").click(function () {
        const receiveRes = $("#receiveRes").val();
        const emailRes = $("#emailRes").val();
        $.ajax({                       // initialize an AJAX request
            type: "POST",
            url: '{% url "annotate_document:updateReceiveRes" %}',
            data: {
                'receiveRes': receiveRes,
                'email': emailRes,
                'csrfmiddlewaretoken':$('input[name=csrfmiddlewaretoken]').val(),
            },
            success: function (data) {
                var message = "You will receive feedback on the results of this project.";
                $("#receiveResponse").html("<p>Your choice has been updated. <br>" + message +"</p>");
            }
        });
    });

    $("#receiveRes").change(function () {
        if ($("#receiveRes").val() == "No"){
            $.ajax({                       // initialize an AJAX request
                type: "POST",
                url: '{% url "annotate_document:updateReceiveRes" %}',
                data: {
                    'receiveRes': "No",
                    'email': '',
                    'csrfmiddlewaretoken':$('input[name=csrfmiddlewaretoken]').val(),
                },
                success: function (data) {
                    message = "You will <b>not</b> recieve feedback on the results of this project.";
                    $("#receiveResponse").html("<p>Your choice has been updated. <br>" + message +"</p>");
                }
            });
        }
    });

    $("#receiveRes").change(function () {
        if ($("#receiveRes").val() == "Yes") {
            $("#email_form").show();
            $("#receiveResponse").html('');
        } else {
            $("#email_form").hide();
            $("#receiveResponse").html('');
        }
    });
</script>
{% endblock %}

templates/annotate_document/video.html
{% extends 'annotate_document/video_base.html' %}

{% block instructions %}
<div class="row">
    <div class="col-12">
        <p>
            The video shows how to use the system to link names to the people to whom they refer.
        </p>
    </div>
</div>
{% endblock %}

{% block navigation %}
{% endblock %}